### ISSUE TITLE
Blank Spaces <cb> (Stadt Wien Project)

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#116]
Currently, blank spaces are being created for words that are connected via column break with <break="no">, for example (in review https://hanslick-online.github.io/hsl-app-dev/v__1855NiederrheinischeMusik-Zeitung2Ausschnitt.html?img=off) at https://github.com/Hanslick-Online/hsl-data-vms/blob/main/data/editions/1855NiederrheinischeMusik-Zeitung2Ausschnitt.xml#L805 and https://github.com/Hanslick-Online/hsl-data-vms/blob/main/data/editions/1855NiederrheinischeMusik-Zeitung2Ausschnitt.xml#L902. I had already tried to fix this with 

![Image](https://github.com/user-attachments/assets/37a747d1-a38b-4d34-8170-9d2c99a2e20f)

but then a line break appeared instead of the space. Please fix for the upcoming release.

**Comment by fsanzl** [comment]
Culprit identified: column break.

**Comment by fsanzl** [comment]
Solved in https://github.com/Hanslick-Online/hsl-app/commit/83e7e359eb0026373d75d7bb83168c06757e60d6

**Comment by AlexanderWilfing** [comment]
Probably related to your current revisions to the blank space issue, this problem has also resurfaced. cb break="no" does seem to work here (e.g. https://hanslick-online.github.io/hsl-app-dev/v__1855NeueZeitschriftfuerMusikAusschnitt.html), but I'll wait with introducing this to the other Stadt Wien Project texts until we are done with the general blank space issue. I'll reopen the issue to keep this on our radar

**Comment by AlexanderWilfing** [comment]
Unfortunately, the issue remains even with cb break="no" (as indicated by another example in issue no. 126):

https://hanslick-online.github.io/hsl-app-dev/v__1855NeueZeitschriftfuerMusikAusschnitt.html?

![Image](https://github.com/user-attachments/assets/7935fd8e-c286-47fd-95a8-05b69033f731)

![Image](https://github.com/user-attachments/assets/c6385f50-e1c7-4376-b8d9-9311c53d0b42)

**Comment by fsanzl** [comment]
I have identified the culprit. We have to apply column-break fix to page breaks as well

**Comment by AlexanderWilfing** [comment]
No problem. Just to double-check: basically what I already tried to do in another instance (see screenshot)? A few weeks ago, this produced an entire line break, but this might not happen because of cb break="no" (which had not been included in the example below), correct? If so, I'll try it out on Monday...

![Image](https://github.com/user-attachments/assets/c185bc51-f577-439b-a228-dda984a147df)

**Comment by fsanzl** [comment]
cb fixed in https://github.com/Hanslick-Online/hsl-app/commit/873aeb0ecdcaa5649f931bcd6864544d8d38b500

pb has the following format in the XML:
```xml
 <lb facs="#facs_8_region_1709375369026_1559_tl_53" n="N053"/>Es ist dies derselbe Irrthum, wie oben bei der <rs type="bibl" ref="#hsl_work_id_346">Ouver
            <pb facs="#facs_9" n="9" xml:id="img_0009"/>
            <cb break="no"/>
      <lb facs="#facs_9_region_1709375404914_1571_tl_1" n="N001" break="no"/>türe</rs> zu <rs type="bibl" ref="#hsl_work_id_4494">Prometheus</rs>, wo auch schon das Thema ge
```

The code is valid, but it misrepresents the actual layout, as it describes a new page starting with a column break, text, and then another column break, i.e., a three-columns page, the first of them empty. I will change the XSL to consider the empty-column case, which is a generalisation that should have been foreseen anyways, but I suggest changing XML-TEI to match the original layout.

**Comment by AlexanderWilfing** [comment]
Anna-Maria, could you please take this on, i.e. changing XML-TEI to mach the original layout after (!!!) the upcoming release? I will write to you as soon as the next release is out, so you can put it on your "to-do-list" for May or June

**Comment by AlexanderWilfing** [comment]
Anna-Maria, the release is online. Please take care of this issue whenever convenient.
