### ISSUE TITLE
blank spaces TOC (NFP reviews and Stadt Wien Project)

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#123]
break="no" currently does not work in terms of TOC. This applies to both the new texts as part of the Stadt Wien Project and the NFP reviews. See, for example https://hanslick-online.github.io/hsl-app-dev/toc_vms.html, the item of 1855-02-16 ("Ton kunst"; https://github.com/Hanslick-Online/hsl-data-vms/blob/4ce3ac7d6eb4a63bffe9168ba268f3193e5cc085/data/editions/1855NeueZeitschriftfuerMusikAusschnitt.xml#L3657) and https://hanslick-online.github.io/hsl-app-dev/toc.html, page 2, the item of 1867-12-11 ("Italieni sches"; https://github.com/Hanslick-Online/hsl-data-ct/blob/21ac921ea0fa7833850f9f7f9ed39da737f7cd0b/data/editions/1867.12.11.xml#L917). This is a minor issue in terms of importance. If it is an easy fix, please address prior to the upcoming release. If the solution would take some time, we can postpone this to the release after next (probably in June/July).

**Comment by AlexanderWilfing** [comment]
Edit: For some reason, the titles and subtitles in the TOC of the Stadt Wien Text are now enclosed in quotation marks, which should not be the case (see https://hanslick-online.github.io/hsl-app-dev/toc_vms.html). Cheers!

**Comment by fsanzl** [comment]
Solved in https://github.com/Hanslick-Online/hsl-app/commit/3ddf0a18898b7b6699427eb84d633e0359f0497e

**Comment by AlexanderWilfing** [comment]
Alas, the blank space TOC issue still exists. See the screenshots of the examples given in my initial comment (Ton kunst; italieni sches): 

![Image](https://github.com/user-attachments/assets/898c37ee-d5ec-4f6f-8ae6-d7b143fd9525)

![Image](https://github.com/user-attachments/assets/094ef964-a255-4697-be56-8ca4eacd3f28)

**Comment by fsanzl** [comment]
Solved in https://github.com/Hanslick-Online/hsl-app/commit/c0d1bc3db6ebc0105a7222321779cef28a11e2c2.

It is a workaround, though. The process is document-dependent, as it relies entirely on the text itself to retrieve data rather than fetching metadata from tei:teiHeader as toc_vms.xsl does
